spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernatedb
    username: root
    password: password
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update